### ISSUE TITLE
Code read sys161

### ISSUE THREAD

**Issue by alexpatel** [Harvard-PRINCESS/Guppy#104]
Child of #99 

https://github.com/Harvard-PRINCESS/sys161-princess

* Read for familiarity w/ simulator, devices, and image load process

**Comment by alexpatel** [comment]
Idea: we could run Barrelfish as a distributed system on a network of Sys161 machines:

> System/161 supports fully transparent debugging, via remote gdb into the simulator. It also provides transparent kernel profiling, statistical monitoring, event tracing (down to the level of individual machine instructions) and one can connect multiple running System/161 instances together into a network using a "hub" program. 

[_About System/161_](http://os161.eecs.harvard.edu/#sys161)

**Comment by ghost** [comment]
Be cool if it worked :-)  Is barrelfish really distributed enough for separate machines?

**Comment by alexpatel** [comment]
I get the impression that the message-passing infra is build to be local to a machine, although from my reading of docs/code  esp. ["Your computer is already a distributed system. Why isn't your OS?"](http://www.barrelfish.org/publications/barrelfish_hotos09.pdf) I don't see a reason you could extend that mechanism on an intra-machine network

**Comment by penlu** [comment]
we concluded this was a standard elf load a month ago, I'm closing this
