### ISSUE TITLE
compile feedback and comments on lincoln phase 2 schedule

### ISSUE THREAD

**Issue by mwookawa** [Harvard-PRINCESS/Guppy#13]

**Comment by dh6713** [comment]
Erm... what am I supposed to do? Where's this schedule?

**Comment by margoseltzer** [comment]
If you go to the issue, you will find it links to here:

https://github.com/Harvard-PRINCESS/documents/blob/master/mitll/CRA%20CP2%20Challenge_Problem_Announcement.docx

- M

**Comment by dh6713** [comment]
I was looking at the issue. That link isn't in it. Also, it's not obvious that that link (which is in a different issue) is pertinent to this one.

**Comment by margoseltzer** [comment]
I got to it by following the discussion using the github interface.

- M

**Comment by dh6713** [comment]
Yes, and i'm using the github interface and there's nothing in this ticket besides the name, and now this string of questions.

**Comment by dh6713** [comment]
Furthermore, that document does not contain any information pertinent to this ticket, as far as I can see...

**Comment by mwookawa** [comment]
curt emailed this to everyone when we last talked to LL. it's also front and center on the lincoln wiki

**Comment by dh6713** [comment]
ok, found it.

The only substantive thought I have so far is that it seems weird to have the RR2 feedback come in the same day RR3 is due; this pretty much guarantees that said feedback won't be reflected in the RR3 deliverable and that's clearly suboptimal.

My suggestion would be to move both the RR2 dates up a week; a week is probably enough...

**Comment by mwookawa** [comment]
i've started a wiki page on the docs wiki, as programmatic discussion between performers is generally typically kept to within the program. https://github.com/Harvard-PRINCESS/documents/wiki/MITLL-Phase2-Schedule-Feedback

**Comment by mwookawa** [comment]
initial feedback was given 6/13 teleconf with LL
