### ISSUE TITLE
proposed: write a hamlet tutorial

### ISSUE THREAD

**Issue by mwookawa** [Harvard-PRINCESS/Guppy#18]
hamlet is thankfully not haskell. further, there is a single hamlet file that defines all capabilities in the barrelfish implementation tree

'tis here: https://github.com/Harvard-PRINCESS/barrelfish/blob/master/capabilities/caps.hl

**Comment by alexpatel** [comment]
@mwookawa is this what I ought to start on next? I am simultaneously trying to work through [Learn You a Haskell for Great Good!](http://learnyouahaskell.com/chapters) and [Write Yourself a Scheme in 48 Hours
50% developed](https://en.wikibooks.org/wiki/Write_Yourself_a_Scheme_in_48_Hours)

**Comment by alexpatel** [comment]
- how to write a hamlet file and understand what it means
- glossary for hamlet stuff
- everything references somewhere in the code (the C associated with the Hamlet code)
- put it in a wiki page

**Comment by alexpatel** [comment]
https://github.com/Harvard-PRINCESS/Guppy/wiki/Hamlet-Tutorial

@mwookawa ready for review, will probably continue to add detail to walkthrough,
