### ISSUE TITLE
Generate capability dependency graphs from Hamlet files

### ISSUE THREAD

**Issue by alexpatel** [Harvard-PRINCESS/Guppy#24]
- the other thing to figure out really quickly is whether their types and subtyping (inherits) - is it actual inheritance or is it something else?
  - do the types and the relationships between them - do they actually form trees or are they arbitrary graphs
  - write up a quick file that converts to dot/graphviz for hls file

https://github.com/Harvard-PRINCESS/barrelfish/blob/master/capabilities/caps.hl
https://github.com/Harvard-PRINCESS/barrelfish/tree/master/tools/hamlet

This issue is being worked on on branch:

https://github.com/Harvard-PRINCESS/barrelfish/tree/capabilities-graphs-%2324

**Comment by alexpatel** [comment]
5/5 - learn basic Haskell, read Hamlet parser and FoF, worked on getting a build going
5/6 - finished with build (had to quit with Vagrant, builds fine with Ubuntu Server on vbox) - rest of today seeing what files hamlet is producing and figure out how re-type restrictions are enforced in C, begin writing graph script in Haskell
5/7 - finish graph script - I'm thinking by midday tomorrow, I think I need about 5 more hours on this

I was planning on writing an executable literate-Haskell script to go with barrelfish/tools/hamlet, @mwookawa ought I to just PR against Harvard-PRINCESS/barrelfish/master?

**Comment by mwookawa** [comment]
@alexpatel PR? if you're asking about whether you should branch, then i think a branch is unnecessary.

also, it occurs to me that adding a mode to the existing hamlet tool that prints a dot file and exits might be much faster and easier to write.

**Comment by alexpatel** [comment]
PR=pull request, sorry

> if you're asking about whether you should branch, then i think a branch is unnecessary.

I will branch, it's more a question of what branch I should send the pull request to

> also, it occurs to me that adding a mode to the existing hamlet tool that prints a dot file and exits might be much faster and easier to write.

Cool, yeah, this seems like the best approach -  right now I'm hoping to just be able to copy the main.hls script that parses the caps file and change it to output the .dot dependencies

**Comment by mwookawa** [comment]
can you name the branch after the issue number? (ie, is this possible? if so, that would be pretty cool. if not, maybe we should name this capability_investigation?)

committing to and branching from our local fork @ https://github.com/Harvard-PRINCESS/barrelfish does not require a pull request.

**Comment by alexpatel** [comment]
yep, i will name it 24-capability-investigation or something.

Even though it's the local fork, I'm just used to submitting work like this as a pull request against the master branch - I will just leave it on the branch for you, though

thanks!

**Comment by mwookawa** [comment]
let's branch it and PR to master later with a goal of an upstream PR ETH. this work would be a nice, small initial contribution to the ETH codebase.

**Comment by alexpatel** [comment]
perfect, love it

**Comment by margoseltzer** [comment]
I’m not averse to including the issue number in the branch name, but I wonder if we should make it the last element so that one can view branches alphabetically and have them mean something.

- M

**Comment by mwookawa** [comment]
Agree. Note also that once you create the branch we can link the branch HEAD from this ticket.
