### ISSUE TITLE
document armv7 pagetable set up on pandaboarfd

### ISSUE THREAD

**Issue by mwookawa** [Harvard-PRINCESS/Guppy#29]
This is mostly done, wiki page is here:

https://github.com/Harvard-PRINCESS/Guppy/wiki/CPU-Boilerplate-Code---ARMv7-(Pandaboard)

**Comment by CrystalMei** [comment]
https://github.com/Harvard-PRINCESS/Guppy/wiki/CPU-Boilerplate-Code---ARMv7-(Pandaboard)
