### ISSUE TITLE
organize guppy wiki with a table of contents tree

### ISSUE THREAD

**Issue by mwookawa** [Harvard-PRINCESS/Guppy#34]

**Comment by penlu** [comment]
see page here: https://github.com/Harvard-PRINCESS/Guppy/wiki/%5BTopical-Index%5D

**Comment by alexpatel** [comment]
@penlu can we just make this the wiki homepage instead of having it on its own page that you also have to find? https://github.com/Harvard-PRINCESS/Guppy/wiki

**Comment by penlu** [comment]
done!
