### ISSUE TITLE
Do all syscalls on ARM and x86 have MD arg setup followed by MI implementation? Child of #33

### ISSUE THREAD

**Issue by marikgoldstein** [Harvard-PRINCESS/Guppy#38]

**Comment by marikgoldstein** [comment]
Note: function implementations that are automatically generated by the Hamlet parser will NOT be shown in kern/syscalls as they are a consequence of the *build* process. These functions will be found somewhere in *build/something/something/cap_predicates* or something with a similar name. It's quite possible that these functions are still shared across archs! _is_ancestor()_ is an example

**Comment by marikgoldstein** [comment]
Question from last week: What would it be like to write a generic barrelfish trapframe. This would involve restructuring the arch-specific syscall setup code into a mapping from arch-specific trapframe to barrelfish trapframe. This might result in more simple and readable code, and it might cause the arch-specific syscall layer to look more consistent across archs (to make arch/arm/syscall and arch/x86_64/syscall to look more similar for example)

**Comment by CrystalMei** [comment]
Wiki updated!
https://github.com/Harvard-PRINCESS/Guppy/wiki/Syscall-details
