### ISSUE TITLE
take inventory of ETH's working barrelfish test list once it is sent.

### ISSUE THREAD

**Issue by marikgoldstein** [Harvard-PRINCESS/Guppy#40]
We should make sure we can run them too.

**Comment by alexpatel** [comment]
https://github.com/Harvard-PRINCESS/Guppy/wiki/Testing-Barrelfish-OS

**Comment by alexpatel** [comment]
To note, what is on that wiki page is just the test list Mothy sent along with the machine list to Margo - ETH may be doing more, I'm going to ping them over the BF list to make sure we have to the entire process documented

**Comment by alexpatel** [comment]
Mothy said: 
> I can send you any/all of these for a given machine, but I can't figure
> out how to export an entire subtree of our MoinMoin internal wiki...

Nevermind, I'm not going to have them spend time dumping that list. I don't see a need now for them to dump the test status for each test for each of their machines, we should only care about which tests pass on our machines...

They said they would run our upstream patches on their infrastructure, so we can look at any differential in which tests are passing/failing across the pond vs. here as they come. @mwookawa good to close?
