### ISSUE TITLE
target arch/platform armv7/pandaboardES does not build with vfs related issue

### ISSUE THREAD

**Issue by mwookawa** [Harvard-PRINCESS/Guppy#48]
xmpl-crystal-readwrite depends on megaraid, which does is not part of the Pandaboard build

logs below:

**Comment by mwookawa** [comment]
ming@nomnomnom:~/research/Guppy/build$  make PandaboardES

arm-linux-gnueabi-gcc -std=c99 -U__STRICT_ANSI__ -Wstrict-prototypes -Wold-style-definition -Wmissing-prototypes -fno-omit-frame-pointer -fno-builtin -nostdinc -U__linux__ -Ulinux -Wall -Wshadow -Wmissing-declarations -Wmissing-field-initializers -Wtype-limits -Wredundant-decls -fno-unwind-tables -Wno-packed-bitfield-compat -marm -fno-stack-protector -mcpu=cortex-a9 -march=armv7-a -mapcs -mabi=aapcs-linux -msingle-pic-base -mpic-register=r9 -DPIC_REGISTER=R9 -fPIE -D__ARM_CORTEX__ -D__ARM_ARCH_7A__ -Wno-unused-but-set-variable -Wno-suggest-attribute=noreturn -Wno-format -DBARRELFISH -DBF_BINARY_PREFIX=\"\" -D_WANT_IO_C99_FORMATS -DCONFIG_SVM -DUSE_KALUGA_DVM -DCONFIG_INTERCONNECT_DRIVER_LMP -DCONFIG_INTERCONNECT_DRIVER_UMP -DCONFIG_FLOUNDER_BACKEND_LMP -DCONFIG_FLOUNDER_BACKEND_UMP -g -O2 -I../include -I../include/arch/arm -I../lib/newlib/newlib/libc/include -I../include/c -I../include/target/arm -I../lib/lwip/src/include/ipv4 -I../lib/lwip/src/include -I./armv7/include -I../lib/ahci/. -I..//lib/ahci/. -I./armv7/lib/ahci/. -o ./armv7/lib/ahci/_for_lib_ahci/sata_fis.o -c ..//lib/ahci/sata_fis.c 
rm -f  ./armv7/lib/libahci.a 
ar crT  ./armv7/lib/libahci.a ./armv7/lib/ahci/_for_lib_ahci/ahci.o ./armv7/lib/ahci/_for_lib_ahci/ahci_util.o ./armv7/lib/ahci/_for_lib_ahci/sata_fis.o ./armv7/lib/ahci/_for_lib_ahci/ahci_dma_pool.o ./armv7/lib/ahci/_for_lib_ahci/ahci_mgmt_flounder_bindings.o ./armv7/lib/ahci/_for_lib_ahci/ata_rw28_flounder_bindings.o ./armv7/lib/ahci/_for_lib_ahci/ahci_mgmt_flounder_extra_bindings.o ./armv7/lib/ahci/_for_lib_ahci/ata_rw28_flounder_extra_bindings.o 
make: *** No rule to make target 'armv7/lib/libmegaraid.a', needed by 'armv7/sbin/examples/xmpl-crystal-readwrite.full'.  Stop.
ming@nomnomnom:~/research/Guppy/build$

**Comment by mwookawa** [comment]
low priority, but when mark or crystal get a chance, can one of you look into and clean up the readwrite example so that it is machine independent?

**Comment by penlu** [comment]
see [pull request](https://github.com/Harvard-PRINCESS/Guppy/pull/52)

**Comment by penlu** [comment]
merged; fixed
