### ISSUE TITLE
Master Ticket: Hake Build System, extracting and visualizing dependency information, adding archs and platforms

### ISSUE THREAD

**Issue by marikgoldstein** [Harvard-PRINCESS/Guppy#49]
What does it take to create a new bfish build for same arch/platform (X86_64_Full versus X86_64_Basic)? [Done: just edit platforms/Hakefile in two places]

What does it take to add new platform but same arch?

For a particular build, what source tree files were used?

For a particular module to run on a particular build, what are the source file dependencies?

How can we visualize these dependencies?

Is there a good way to store dependency information in a database to be queried at these various levels?

How can we use CScope?

**Comment by marikgoldstein** [comment]
parent of 50

**Comment by marikgoldstein** [comment]
parent of #44

**Comment by mwookawa** [comment]
is this basically done? are there caveats to your pulling of markfile into dev?

**Comment by marikgoldstein** [comment]
This was pulled a while ago but the issue wasn't closed. Sorry about that.
