### ISSUE TITLE
gather information on operating system porting costs

### ISSUE THREAD

**Issue by penlu** [Harvard-PRINCESS/Guppy#53]
There's information available re. operating system porting costs for various projects:
* Microsoft empirical software engineering work
* F-35 development costs

Hoping to collate numbers on things like:
* total cost of a port
* appx. number of dev-hours expended
* cost per commit

**Comment by penlu** [comment]
Suggested to talk to business school research librarians for analyst reports on costs. Alex? I could also do this at some point if it's preferred!

**Comment by mwookawa** [comment]
alex, can you take ownership of this? we do really just want one document with large numbers on it. i'd like to free you and eric for DSL compiler hacking asap.

**Comment by penlu** [comment]
* https://www.microsoft.com/en-us/research/people/nachin/
* https://github.com/mwookawa/misc

**Comment by alexpatel** [comment]
I've compiled everything so far into a wiki page: https://github.com/Harvard-PRINCESS/documents/wiki/OS-Porting-Costs

HBS front-desk librarian gave a few databases, but I've been through the ones to which I have access and haven't had much luck 

What's left:
- still need better sources - HBS librarian said to e-mail to set up a proper sit-down with a research staffer, will do tomorrow
- pull out various $/hours numbers from sources (so far every # I've seen is uncited/poorly sourced)
- summarize porting cost estimate models from various papers in *Papers* section
- explore more into porting for: applications, embedded systems, video games, military systems
